spring:
  servlet:
    multipart:
      file-size-threshold: 1024MB
      max-file-size: 10GB
      max-request-size: 100GB
  datasource:
    #url: ENC(AmjDJqwXWxXbNLxT2tqrt7evRCK8NdAJ/KVEtB7usTsoUzlncqDsMcIiJbPEo2eR7470koIhMEpI1Ut2Ywum/kwxsbK3eM7x) ?? ???
    url: jdbc:mysql://localhost:3306/movie?serverTimezone=Asia/Seoul
    username: ENC(5/AhqAagHOPYLAK/ZmVpWQ==)
    password: ENC(7tcKhS5JXkdK1pfbDxbgHA==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
server:
  port: 80

---
spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      location: ./test

---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      location: /movie/temp