app:
  secret-key: ${JWT_SECRET_KEY}

server:
  error:
    whitelabel:
      enabled: false

spring:
    application:
        name: backend
    output:
        ansi:
            enabled: always
        
# swagger
springdoc:
    api-docs:
        path: /docs
    swagger-ui:
        path: /swagger-ui
        display-request-duration: true
    cache:
        disabled: true
    paths-to-match: /api/v1/**
