app:
    secret-key: ${JWT_SECRET_KEY}
        

scheduler:
    task:
        kobis-movie-search:
            cron: ${KOBIS_MOVIE_SEARCH_TASK_CRON:-}
        movie-notice:
            cron: ${MOVIE_NOTICE_TASK_CRON:-}
    thread-pool-size: ${SHCEDULER_THREAD_POOL_SIZE}

# kobis 사 api 정보
kobis:
    base-url: ${KOBIS_BASE_URL}
    movie-weekly-info-url: ${KOBIS_MOVIE_WEEKLY_INFO_URL}
    movie-info-url: ${KOBIS_MOVIE_INFO_URL}
    api-key: ${KOBIS_API_KEY}

# p6spy log 작동 속성
decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    root: info

server:
  error:
    whitelabel:
      enabled: false

spring:
    # mail 발송 속성
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_ID}
        password: ${MAIL_PASSWORD}
        properties:
            mail.smtp.auth: true
            mail.smtp.connectiontimeout: 5000
            mail.smtp.timeout: 5000
            mail.smtp.starttls.enable: true

    application:
        name: backend
    output:
        ansi:
            enabled: always
# jpa
    datasource:
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

 
    jpa:
        database: mysql
        
# swagger
springdoc:
    api-docs:
        path: /docs
    swagger-ui:
        path: /swagger-ui
        display-request-duration: true
    cache:
        disabled: true
    paths-to-match: /api/v1/**