app:
  secret-key: ${JWT_SECRET_KEY}

logging:
  level:
    root: info

server:
  error:
    whitelabel:
      enabled: false

spring:
    application:
        name: backend
    output:
        ansi:
            enabled: always
# jpa
    datasource:
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

 
    jpa:
        show_sql: false
        database: mysql
        properties:
            hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
# swagger
springdoc:
    api-docs:
        path: /docs
    swagger-ui:
        path: /swagger-ui
        display-request-duration: true
    cache:
        disabled: true
    paths-to-match: /api/v1/**
