spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      file-size-threshold: 1024MB
      max-file-size: 10GB
      max-request-size: 100GB

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  profiles:
    active: test
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    #url: ENC(AmjDJqwXWxXbNLxT2tqrt7evRCK8NdAJ/KVEtB7usTsoUzlncqDsMcIiJbPEo2eR7470koIhMEpI1Ut2Ywum/kwxsbK3eM7x)
    url: jdbc:mysql://localhost:3306/movie?serverTimezone=Asia/Seoul
    username: ENC(5/AhqAagHOPYLAK/ZmVpWQ==)
    password: ENC(7tcKhS5JXkdK1pfbDxbgHA==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
  servlet:
    multipart:
      location: C:\movie\temp
server:
  port: 8080

movie:
  path:
    upload: C:\movie\store\
---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      location: /movie/temp

server:
  port: 80

movie:
  path:
    upload: /movie/store/

---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/test;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect


logging.level:
    org.hibernate.SQL: debug