version: '3'
services:
  backend:
    image: ehaakdl/movie-backend:latest
    container_name: backend
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ID: ${MAIL_ID}
      OAUTH_GOOGLE_CLIENT_SECRET: ${OAUTH_GOOGLE_CLIENT_SECRET}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SHCEDULER_THREAD_POOL_SIZE: ${SHCEDULER_THREAD_POOL_SIZE}
      KOBIS_BASE_URL: ${KOBIS_BASE_URL}
      KOBIS_API_KEY: ${KOBIS_API_KEY}
      KOBIS_MOVIE_WEEKLY_INFO_URL: ${KOBIS_MOVIE_WEEKLY_INFO_URL}
      KOBIS_MOVIE_INFO_URL: ${KOBIS_MOVIE_INFO_URL}
      KOBIS_MOVIE_SEARCH_TASK_CRON: ${KOBIS_MOVIE_SEARCH_TASK_CRON}
      MOVIE_NOTICE_TASK_CRON: ${MOVIE_NOTICE_TASK_CRON}
    ports:
      - 8080:8080
  db:
    image: mysql:8.0.32
    container_name: db
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      TZ: ${MYSQL_TIME_ZONE}
    ports:
      - 3306:3306
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      # - ./data/mysql:/var/lib/mysql --user 1000
      - ./conf/my.cnf:/etc/mysql/my.cnf
